// Every story owns a robot, a way of moving and a kind of goal. The map legend:
//   .  empty floor          #  wall, bush, crate, crater or fence (the story picks the look)
//   *  a thing to collect   1-9  things to collect in this order
//   s c t  parcels (star, circle, triangle)   S C T  stations with the same sign
//   o q  floor switches (circle, square)      O Q  gates opened by the switch of that shape
//   ~  water: no walking, but a jump crosses it
//   < > ^ v  conveyor belts that carry the robot one cell in that direction
//   b  a snowball the robot pushes           x  the mark a snowball has to reach
// The robot start is given separately, because it may stand on a parcel.
// `solution` is the shortest program; the tests confirm that with a search.
const ROBO_STORIES = [
  {
    id: "post",
    title: "Post Office",
    lead: "The robot carries a parcel to the station with the same sign. Arrows move it, the yellow hand picks the parcel up and the red hand puts it down.",
    emoji: "📦",
    movement: "arrows",
    theme: "meadow",
    accessory: "cap",
    levels: [
      {
        title: "First Parcel",
        goal: "The parcel is right under the robot. Pick it up and carry it to the station.",
        hint: "Pick up, three steps right, put down.",
        map: [
          "......",
          ".s..S.",
          "......",
        ],
        robot: { x: 1, y: 1, facing: "east" },
        commands: ["pick", "right", "drop"],
        solution: ["pick", "right", "right", "right", "drop"],
      },
      {
        title: "One Step Back",
        goal: "The parcel is behind the robot. Step left first, then deliver it.",
        hint: "Step left, pick up, four steps right, put down.",
        map: [
          "......",
          ".s...S",
          "......",
        ],
        robot: { x: 2, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop"],
        solution: ["left", "pick", "right", "right", "right", "right", "drop"],
      },
      {
        title: "Look Up",
        goal: "The parcel waits above the robot. A new card moves the robot up.",
        hint: "Step up, pick up, three steps right, put down.",
        map: [
          "......",
          ".s..S.",
          "......",
        ],
        robot: { x: 1, y: 2, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up"],
        solution: ["up", "pick", "right", "right", "right", "drop"],
      },
      {
        title: "Around the Corner",
        goal: "The station stands in the top row. Combine steps right and steps up.",
        hint: "Two steps right, pick up, two up, two right, put down.",
        map: [
          "....S.",
          "......",
          "..s...",
        ],
        robot: { x: 0, y: 2, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up"],
        solution: ["right", "right", "pick", "up", "up", "right", "right", "drop"],
      },
      {
        title: "Long Road Down",
        goal: "The parcel is at the top and the station at the bottom. The last arrow card moves the robot down.",
        hint: "Two up, pick up, four left, two down, put down.",
        map: [
          "....s.",
          "......",
          "S.....",
        ],
        robot: { x: 4, y: 2, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["up", "up", "pick", "left", "left", "left", "left", "down", "down", "drop"],
      },
      {
        title: "The Bush",
        goal: "A bush blocks the straight way. Go around it.",
        hint: "Two right, pick up, up, two right, up, put down.",
        map: [
          "....S.",
          "......",
          "..s#..",
        ],
        robot: { x: 0, y: 2, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["right", "right", "pick", "up", "right", "right", "up", "drop"],
      },
      {
        title: "Two Bushes",
        goal: "Two bushes stand in a column. The only way past them is below.",
        hint: "Two right, pick up, down, two right, up, right, put down.",
        map: [
          "...#..",
          "..s#.S",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["right", "right", "pick", "down", "right", "right", "up", "right", "drop"],
      },
      {
        title: "Big Meadow",
        goal: "A bigger field. Find the gap in the bushes before you pick up the parcel.",
        hint: "Two right, pick up, up, three right, two down, right, put down.",
        map: [
          ".......",
          "..s#...",
          "...#..S",
          "....#..",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["right", "right", "pick", "up", "right", "right", "right", "down", "down", "right", "drop"],
      },
    ],
  },
  {
    id: "gates",
    title: "Gate Yard",
    lead: "A closed gate blocks a cell. The robot opens it by stepping on the floor switch with the same shape. Later, parcels get signs and there are two of them.",
    emoji: "🚪",
    movement: "arrows",
    theme: "yard",
    accessory: "key",
    levels: [
      {
        title: "Switch on the Way",
        goal: "The floor switch lies right before the gate. Walk over it and the gate opens.",
        hint: "Pick up, five steps right over the switch, up, put down.",
        map: [
          "......",
          ".....S",
          "s.oO..",
        ],
        robot: { x: 0, y: 2, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["pick", "right", "right", "right", "right", "right", "up", "drop"],
      },
      {
        title: "Small Detour",
        goal: "The switch is one row above the road. Step onto it, then continue.",
        hint: "Pick up, two right, up, down, three right, put down.",
        map: [
          "..o...",
          "s..O.S",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["pick", "right", "right", "up", "down", "right", "right", "right", "drop"],
      },
      {
        title: "Open First",
        goal: "Open the gate before you take the parcel.",
        hint: "Left onto the switch, right, up, pick up, three right, put down.",
        map: [
          "......",
          "..sO.S",
          ".o....",
        ],
        robot: { x: 2, y: 2, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["left", "right", "up", "pick", "right", "right", "right", "drop"],
      },
      {
        title: "Same Sign",
        goal: "Two stations, one parcel. The star parcel belongs to the star station.",
        hint: "Pick up, three right past the circle station, put down.",
        map: [
          "......",
          ".sC.S.",
          "......",
        ],
        robot: { x: 1, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["pick", "right", "right", "right", "drop"],
      },
      {
        title: "Two Parcels",
        goal: "Two parcels, two stations. The robot carries one parcel at a time.",
        hint: "Up, pick up, right, put down, left, two down, pick up, right, put down.",
        map: [
          ".sS...",
          "......",
          ".cC...",
        ],
        robot: { x: 1, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["up", "pick", "right", "drop", "left", "down", "down", "pick", "right", "drop"],
      },
      {
        title: "Crossing Roads",
        goal: "The stations are on the far corners. Either parcel may go first.",
        hint: "Up, pick up, two right, two down, put down, two left, pick up, two right, two up, put down.",
        map: [
          "..s.C.",
          "......",
          "..c.S.",
        ],
        robot: { x: 2, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["up", "pick", "right", "right", "down", "down", "drop", "left", "left", "pick", "right", "right", "up", "up", "drop"],
      },
      {
        title: "Good Order",
        goal: "A crate is in the way. One delivery order is shorter than the other, but both work.",
        hint: "Down, right, pick up, left, put down, two right, up, pick up, right, put down.",
        map: [
          ".#sS..",
          "Cc....",
          "......",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["down", "right", "pick", "left", "drop", "right", "right", "up", "pick", "right", "drop"],
      },
      {
        title: "Two Shapes",
        goal: "A round switch opens the round gate, a square switch opens the square gate. Pick the shorter way.",
        hint: "Pick up, up onto the round switch, two right, down, three right through the round gate, put down.",
        map: [
          ".o.#..",
          "s..O.S",
          "...Q..",
          ".q.#..",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["left", "pick", "right", "drop", "up", "down"],
        solution: ["pick", "up", "right", "right", "down", "right", "right", "right", "drop"],
      },
    ],
  },
  {
    id: "charge",
    title: "Charging Lab",
    lead: "This robot walks forward and turns. Its headlight shows where it looks. Batteries charge it, and a floor switch opens the door with the same shape.",
    emoji: "🔋",
    movement: "turns",
    theme: "lab",
    accessory: "bolt",
    levels: [
      {
        title: "Straight Ahead",
        goal: "The robot already looks at the battery. Three steps forward.",
        hint: "Forward, forward, forward.",
        map: [
          "......",
          "...*..",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["forward"],
        solution: ["forward", "forward", "forward"],
      },
      {
        title: "First Turn",
        goal: "The battery is not straight ahead. Turn the robot so its headlight points at it.",
        hint: "Two forward, turn left, two forward.",
        map: [
          "..*...",
          "......",
          "......",
        ],
        robot: { x: 0, y: 2, facing: "east" },
        commands: ["forward", "turnLeft", "turnRight"],
        solution: ["forward", "forward", "turnLeft", "forward", "forward"],
      },
      {
        title: "Around the Wall",
        goal: "Walls block the straight way. Turn twice to get around.",
        hint: "Forward, turn right, two forward, turn left, two forward.",
        map: [
          ".....",
          "..*..",
          "#....",
          "...#.",
          ".....",
        ],
        robot: { x: 0, y: 4, facing: "north" },
        commands: ["forward", "turnLeft", "turnRight"],
        solution: ["forward", "turnRight", "forward", "forward", "turnLeft", "forward", "forward"],
      },
      {
        title: "Round Door",
        goal: "The round door is closed. Step on the round switch first.",
        hint: "Forward onto the switch, turn right, two forward, turn left, three forward.",
        map: [
          "..*..",
          "..O..",
          "##.##",
          "o....",
          ".....",
        ],
        robot: { x: 0, y: 4, facing: "north" },
        commands: ["forward", "turnLeft", "turnRight"],
        solution: ["forward", "turnRight", "forward", "forward", "turnLeft", "forward", "forward", "forward"],
      },
      {
        title: "One, Then Two",
        goal: "The batteries have numbers. Take battery 1 before battery 2.",
        hint: "Four forward, turn left, three forward.",
        map: [
          ".....",
          "....2",
          ".###.",
          ".....",
          "..1..",
        ],
        robot: { x: 0, y: 4, facing: "east" },
        commands: ["forward", "turnLeft", "turnRight"],
        solution: ["forward", "forward", "forward", "forward", "turnLeft", "forward", "forward", "forward"],
      },
      {
        title: "Two Doors",
        goal: "Two switches and two doors in a row. Each switch opens the door of its own shape.",
        hint: "Four forward, turn left, four forward.",
        map: [
          "####*",
          "####Q",
          "####q",
          "####O",
          ".o...",
        ],
        robot: { x: 0, y: 4, facing: "east" },
        commands: ["forward", "turnLeft", "turnRight"],
        solution: ["forward", "forward", "forward", "forward", "turnLeft", "forward", "forward", "forward", "forward"],
      },
      {
        title: "Pick a Switch",
        goal: "Two switches, two doors, one battery. Either shape leads to the battery.",
        hint: "Turn right, forward onto the square switch, turn left, four forward through the square door, turn left, forward.",
        map: [
          "o.#..",
          "..O.*",
          "q.Q..",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["forward", "turnLeft", "turnRight"],
        solution: ["turnRight", "forward", "turnLeft", "forward", "forward", "forward", "forward", "turnLeft", "forward"],
      },
      {
        title: "Full Circuit",
        goal: "Two batteries in order, two doors. Plan the whole trip before you press play.",
        hint: "Two forward over the square switch, turn left, two forward over battery 1 and the round switch, turn right, two forward, turn left, two forward.",
        map: [
          "....2",
          ".###Q",
          ".#o.O",
          ".#1#.",
          ".q...",
        ],
        robot: { x: 0, y: 4, facing: "east" },
        commands: ["forward", "turnLeft", "turnRight"],
        solution: ["forward", "forward", "turnLeft", "forward", "forward", "turnRight", "forward", "forward", "turnLeft", "forward", "forward"],
      },
    ],
  },
  {
    id: "rover",
    title: "Mars Rover",
    lead: "The rover walks forward and turns, like in the lab. The new card ×2 repeats the last two moves, so long roads take fewer cards. Every crystal has to be collected.",
    emoji: "🚀",
    movement: "turns",
    theme: "mars",
    accessory: "flag",
    levels: [
      {
        title: "Repeat Two",
        goal: "Four steps with three cards: forward, forward, then ×2 repeats them.",
        hint: "Forward, forward, ×2.",
        map: [
          "......",
          "....*.",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["forward", "repeat"],
        solution: ["forward", "forward", "repeat"],
      },
      {
        title: "Twice Twice",
        goal: "Six steps. Two ×2 cards in a row repeat the same two moves again.",
        hint: "Forward, forward, ×2, ×2.",
        map: [
          ".......",
          "......*",
          ".......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["forward", "repeat"],
        solution: ["forward", "forward", "repeat", "repeat"],
      },
      {
        title: "Long Corner",
        goal: "Up the column, then along the top row. Use ×2 where the road is straight.",
        hint: "Three forward, turn right, forward, forward, ×2, forward.",
        map: [
          ".....*",
          "......",
          "......",
          "......",
        ],
        robot: { x: 0, y: 3, facing: "north" },
        commands: ["forward", "turnLeft", "turnRight", "repeat"],
        solution: ["forward", "forward", "forward", "turnRight", "forward", "forward", "repeat", "forward"],
      },
      {
        title: "The Long Way",
        goal: "A winding canyon. Every long straight is four steps: forward, forward, ×2.",
        hint: "Forward, forward, ×2, turn left, two forward, turn left, forward, forward, ×2, turn right, two forward.",
        map: [
          "*....",
          ".####",
          ".....",
          "####.",
          ".....",
        ],
        robot: { x: 0, y: 4, facing: "east" },
        commands: ["forward", "turnLeft", "turnRight", "repeat"],
        solution: ["forward", "forward", "repeat", "turnLeft", "forward", "forward", "turnLeft", "forward", "forward", "repeat", "turnRight", "forward", "forward"],
      },
      {
        title: "There and Back",
        goal: "Crystals at both ends of the road. Two turns in a row turn the rover around.",
        hint: "Three forward, turn right twice, forward, forward, ×2, ×2.",
        map: [
          ".......",
          "*.....*",
          ".......",
        ],
        robot: { x: 3, y: 1, facing: "east" },
        commands: ["forward", "turnLeft", "turnRight", "repeat"],
        solution: ["forward", "forward", "forward", "turnRight", "turnRight", "forward", "forward", "repeat", "repeat"],
      },
      {
        title: "Crater Field",
        goal: "Two crystals in the far corners and craters in between. The top road is long and straight.",
        hint: "Three forward, turn right, two forward, turn right, forward, forward, ×2, ×2.",
        map: [
          "*.....*",
          ".#.#.#.",
          ".......",
        ],
        robot: { x: 3, y: 2, facing: "west" },
        commands: ["forward", "turnLeft", "turnRight", "repeat"],
        solution: ["forward", "forward", "forward", "turnRight", "forward", "forward", "turnRight", "forward", "forward", "repeat", "repeat"],
      },
      {
        title: "Three Crystals",
        goal: "Three crystals. Any order works; the shortest trip earns three stars.",
        hint: "Three forward, turn right, forward, forward, ×2, ×2, forward, turn right, three forward.",
        map: [
          "*......*",
          ".....#..",
          "..#.....",
          ".......*",
        ],
        robot: { x: 0, y: 3, facing: "north" },
        commands: ["forward", "turnLeft", "turnRight", "repeat"],
        solution: ["forward", "forward", "forward", "turnRight", "forward", "forward", "repeat", "repeat", "forward", "turnRight", "forward", "forward", "forward"],
      },
      {
        title: "Grand Tour",
        goal: "Four crystals in the four corners. Repeat cards keep the program short enough to fit.",
        hint: "Forward, turn right, forward, forward, ×2, turn right, three forward, turn right, forward, forward, ×2.",
        map: [
          "*...*",
          ".....",
          ".#.#.",
          "*...*",
        ],
        robot: { x: 0, y: 1, facing: "north" },
        commands: ["forward", "turnLeft", "turnRight", "repeat"],
        solution: ["forward", "turnRight", "forward", "forward", "repeat", "turnRight", "forward", "forward", "forward", "turnRight", "forward", "forward", "repeat"],
      },
    ],
  },
  {
    id: "clean",
    title: "Clean Room",
    lead: "The robot vacuums every dusty spot. Arrows move it, ×2 repeats the last two moves, and the furniture is in the way.",
    emoji: "🧹",
    movement: "arrows",
    theme: "room",
    accessory: "broom",
    levels: [
      {
        title: "One Row",
        goal: "Four dusty spots in a row. Right, right, then ×2.",
        hint: "Right, right, ×2.",
        map: [
          "......",
          ".****.",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["left", "right", "repeat"],
        solution: ["right", "right", "repeat"],
      },
      {
        title: "Two Rows",
        goal: "Clean one row, step down, clean the other row backwards.",
        hint: "Right, right, ×2, down, left, left, ×2.",
        map: [
          ".****.",
          ".****.",
          "......",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["left", "right", "down", "repeat"],
        solution: ["right", "right", "repeat", "down", "left", "left", "repeat"],
      },
      {
        title: "Around the Table",
        goal: "Dust all around the table. Walk the loop.",
        hint: "Left, left, ×2, left, down, down, right, right, ×2, up.",
        map: [
          "*****.",
          "*###*.",
          "*****.",
          "......",
        ],
        robot: { x: 5, y: 0, facing: "west" },
        commands: ["left", "right", "up", "down", "repeat"],
        solution: ["left", "left", "repeat", "left", "down", "down", "right", "right", "repeat", "up"],
      },
      {
        title: "Under the Sofa",
        goal: "A long strip of dust under the sofa. Two ×2 cards in a row.",
        hint: "Down, right, right, ×2, ×2.",
        map: [
          ".#######",
          ".******.",
          "........",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["left", "right", "up", "down", "repeat"],
        solution: ["down", "right", "right", "repeat", "repeat"],
      },
      {
        title: "Zigzag",
        goal: "Three rows of dust. Right, then left, then right again.",
        hint: "Right, right, ×2, down, left, left, ×2, down, right, right, ×2.",
        map: [
          ".****",
          ".****",
          ".****",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["left", "right", "up", "down", "repeat"],
        solution: ["right", "right", "repeat", "down", "left", "left", "repeat", "down", "right", "right", "repeat"],
      },
      {
        title: "Two Carpets",
        goal: "Two dusty carpets with a long shelf between them. Go around the end of the shelf.",
        hint: "Right, right, ×2, right, down, down, left, left, ×2.",
        map: [
          ".****.",
          "#####.",
          ".****.",
          "......",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["left", "right", "up", "down", "repeat"],
        solution: ["right", "right", "repeat", "right", "down", "down", "left", "left", "repeat"],
      },
      {
        title: "Corridor",
        goal: "A long corridor with dust in both halves. Find the shortest loop.",
        hint: "Right, right, ×2, ×2, down, down, left, left, left, ×2.",
        map: [
          "........",
          ".******.",
          ".#####..",
          ".******.",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["left", "right", "up", "down", "repeat"],
        solution: ["right", "right", "repeat", "repeat", "down", "down", "left", "left", "left", "repeat"],
      },
      {
        title: "Whole Room",
        goal: "Three dusty rows between the shelves. Without ×2 the program does not fit into the strip.",
        hint: "Right, right, ×2, right, down, down, left, left, ×2, left, down, down, right, right, ×2.",
        map: [
          ".****.",
          "#####.",
          ".****.",
          ".#####",
          ".****.",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["left", "right", "up", "down", "repeat"],
        solution: ["right", "right", "repeat", "right", "down", "down", "left", "left", "repeat", "left", "down", "down", "right", "right", "repeat"],
      },
    ],
  },
  {
    id: "snow",
    title: "Snow Yard",
    lead: "It snowed in the yard. When the robot walks into a snowball, the ball rolls one cell ahead. Roll every snowball onto its mark and it turns into a snowman.",
    emoji: "⛄",
    movement: "arrows",
    theme: "snow",
    accessory: "scarf",
    levels: [
      {
        title: "First Push",
        goal: "The snowball lies in front of the robot. Walk into it and it rolls towards the mark.",
        hint: "Three steps right.",
        map: [
          "......",
          ".b..x.",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["right"],
        solution: ["right", "right", "right"],
      },
      {
        title: "Push Up",
        goal: "The mark is above the snowball. Stand under the ball and push it up.",
        hint: "Two right, two up.",
        map: [
          "..x..",
          ".....",
          "..b..",
          ".....",
        ],
        robot: { x: 0, y: 3, facing: "east" },
        commands: ["right", "up"],
        solution: ["right", "right", "up", "up"],
      },
      {
        title: "Down the Hill",
        goal: "The mark is below the ball. The last arrow card pushes down.",
        hint: "Two right, two down.",
        map: [
          "......",
          "..b...",
          "......",
          "..x...",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["right", "up", "down"],
        solution: ["right", "right", "down", "down"],
      },
      {
        title: "From the Other Side",
        goal: "The mark is on the left, so the ball has to be pushed from the right. Walk around it first.",
        hint: "Two right, up, two left.",
        map: [
          "......",
          "x.b...",
          "......",
        ],
        robot: { x: 1, y: 2, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["right", "right", "up", "left", "left"],
      },
      {
        title: "Round the Corner",
        goal: "The mark is not in line with the ball. Push it right, then walk around and push it down.",
        hint: "Two right, up, right, down.",
        map: [
          ".....",
          ".b...",
          "...x.",
          ".....",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["right", "right", "up", "right", "down"],
      },
      {
        title: "The Fence",
        goal: "A fence blocks the straight road. A snowball cannot roll through a fence, so take it below.",
        hint: "Right, up, right, down, left, down, right.",
        map: [
          ".....",
          ".b.#.",
          "...x.",
          ".....",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["right", "up", "right", "down", "left", "down", "right"],
      },
      {
        title: "Two Snowmen",
        goal: "Two snowballs, two marks. Each ball is pushed from its own side.",
        hint: "Up, three right, down, right, down, two left.",
        map: [
          ".....",
          ".b..x",
          ".....",
          ".x.b.",
        ],
        robot: { x: 0, y: 2, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["up", "right", "right", "right", "down", "right", "down", "left", "left"],
      },
      {
        title: "Snow Fort",
        goal: "Two balls and a fence. Roll the left ball down first, then take the other one right and down. A ball rolled into a corner is stuck, and the card that did it trembles.",
        hint: "Three down, up, right, up, right, up, right, two down.",
        map: [
          "......",
          ".b.b..",
          "......",
          "..#.x.",
          ".x....",
        ],
        robot: { x: 1, y: 0, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["down", "down", "down", "up", "right", "up", "right", "up", "right", "down", "down"],
      },
    ],
  },
  {
    id: "factory",
    title: "Toy Factory",
    lead: "Conveyor belts run across the factory floor. When the robot steps onto a belt, the belt carries it along to the end. Collect every gear.",
    emoji: "⚙️",
    movement: "arrows",
    theme: "factory",
    accessory: "wrench",
    levels: [
      {
        title: "Ride the Belt",
        goal: "One step onto the belt. The belt carries the robot all the way to the gear.",
        hint: "One step right.",
        map: [
          "......",
          ".>>>*.",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["right"],
        solution: ["right"],
      },
      {
        title: "Belt Up",
        goal: "Two belts: one runs right, one runs up. A belt stops where the floor begins.",
        hint: "Right, then up.",
        map: [
          "...*..",
          "...^..",
          "...^..",
          ".>>...",
        ],
        robot: { x: 0, y: 3, facing: "east" },
        commands: ["right", "up"],
        solution: ["right", "up"],
      },
      {
        title: "Long Ride",
        goal: "This belt turns a corner on its own. Step onto it and watch the ride.",
        hint: "Right, then down.",
        map: [
          "......",
          ".v....",
          ".v....",
          ".>>>*.",
        ],
        robot: { x: 0, y: 0, facing: "east" },
        commands: ["right", "up", "down"],
        solution: ["right", "down"],
      },
      {
        title: "Wrong Way",
        goal: "The belt in front of the robot runs the wrong way and carries it back. Go along the row above; the belt at its end runs up.",
        hint: "Up, five left.",
        map: [
          "*.....",
          "^.....",
          "^.>>>.",
          "......",
        ],
        robot: { x: 5, y: 2, facing: "west" },
        commands: ["right", "up", "down", "left"],
        solution: ["up", "left", "left", "left", "left", "left"],
      },
      {
        title: "Two Gears",
        goal: "Two gears, two belts. The belt above the robot runs up, the belt beside it runs right.",
        hint: "Up, right, three down.",
        map: [
          "*.....",
          "^.....",
          "^.....",
          ".>>>*.",
        ],
        robot: { x: 0, y: 3, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["up", "right", "down", "down", "down"],
      },
      {
        title: "Across the Belt",
        goal: "A belt runs down across the road. It carries the robot to the first gear, and the road goes on from there.",
        hint: "Three right onto the belt, three more right, two up.",
        map: [
          "...v...",
          "...v..*",
          "...v...",
          "...*...",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["right", "right", "right", "right", "right", "right", "up", "up"],
      },
      {
        title: "Three Gears",
        goal: "Three gears. The last one waits at the end of a long belt.",
        hint: "Up, right, two up, two right.",
        map: [
          ".*.v...",
          "...v...",
          "*..>>*.",
          ".......",
        ],
        robot: { x: 0, y: 3, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["up", "right", "up", "up", "right", "right"],
      },
      {
        title: "Big Factory",
        goal: "Three gears and three belts. One belt runs the wrong way, one runs up to the first gear and one runs down to the last.",
        hint: "Up onto the belt, six right, left, down onto the belt, left.",
        map: [
          "*.....*",
          "^.>>>v.",
          "^....v.",
          "^<<<.v.",
          "....*..",
        ],
        robot: { x: 1, y: 4, facing: "east" },
        commands: ["right", "up", "down", "left"],
        solution: ["up", "right", "right", "right", "right", "right", "right", "left", "down", "left"],
      },
    ],
  },
  {
    id: "pond",
    title: "Lily Pond",
    lead: "Rubber ducks floated away across the pond. The robot walks on the lily pads, and the new card makes it jump over one cell of water. Gather every duck.",
    emoji: "🦆",
    movement: "turns",
    theme: "pond",
    accessory: "ring",
    levels: [
      {
        title: "Hop",
        goal: "Water lies between the robot and the duck. The new card jumps over one cell.",
        hint: "Jump.",
        map: [
          ".....",
          ".~*..",
          ".....",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["jump"],
        solution: ["jump"],
      },
      {
        title: "Walk and Hop",
        goal: "Walk to the edge of the water first, then jump. A jump that lands in the water stops the run.",
        hint: "Forward, jump, jump.",
        map: [
          "......",
          "..~.~*",
          "......",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["jump", "forward"],
        solution: ["forward", "jump", "jump"],
      },
      {
        title: "Turn at the Water",
        goal: "The duck is up the column. Turn the headlight towards the water, then jump.",
        hint: "Forward, turn left, jump.",
        map: [
          "..*...",
          "..~...",
          "......",
        ],
        robot: { x: 1, y: 2, facing: "east" },
        commands: ["jump", "forward", "turnLeft", "turnRight"],
        solution: ["forward", "turnLeft", "jump"],
      },
      {
        title: "Two Ducks",
        goal: "Two ducks and water on every side. Jump, turn, jump, turn, jump.",
        hint: "Jump, turn left, jump, turn left, jump.",
        map: [
          ".~*..",
          "~~~..",
          "*~...",
        ],
        robot: { x: 2, y: 2, facing: "north" },
        commands: ["jump", "forward", "turnLeft", "turnRight"],
        solution: ["jump", "turnLeft", "jump", "turnLeft", "jump"],
      },
      {
        title: "The Island",
        goal: "A duck sits on a small island. Jump onto it, jump off it, then turn to the last duck.",
        hint: "Jump, jump, turn right, jump.",
        map: [
          "..~...",
          ".~*~..",
          "..~.~.",
          "....*.",
        ],
        robot: { x: 0, y: 1, facing: "east" },
        commands: ["jump", "forward", "turnLeft", "turnRight"],
        solution: ["jump", "jump", "turnRight", "jump"],
      },
      {
        title: "Stepping Stones",
        goal: "Walk where the pads touch and jump where water lies between them.",
        hint: "Forward, turn right, jump, jump, turn right, forward.",
        map: [
          ".~.~.",
          ".....",
          "*~.~.",
          "....*",
        ],
        robot: { x: 0, y: 3, facing: "north" },
        commands: ["jump", "forward", "turnLeft", "turnRight"],
        solution: ["forward", "turnRight", "jump", "jump", "turnRight", "forward"],
      },
      {
        title: "Zigzag Pond",
        goal: "The road turns twice. Plan every turn before the jump.",
        hint: "Turn left, jump, turn right, jump, jump, turn right, forward, jump.",
        map: [
          "*~.~.",
          "~~.~.",
          "....~",
          ".~.~*",
        ],
        robot: { x: 0, y: 2, facing: "east" },
        commands: ["jump", "forward", "turnLeft", "turnRight"],
        solution: ["turnLeft", "jump", "turnRight", "jump", "jump", "turnRight", "forward", "jump"],
      },
      {
        title: "Big Pond",
        goal: "Three ducks around the whole pond. Walk where the pads touch, jump everywhere else.",
        hint: "Forward, jump, jump, forward, turn left, jump, jump, turn left, three jumps.",
        map: [
          "*~.~.~*",
          "~~~~~~~",
          "~~~~~~.",
          "~~~~~~~",
          "..~.~.*",
        ],
        robot: { x: 0, y: 4, facing: "east" },
        commands: ["jump", "forward", "turnLeft", "turnRight"],
        solution: ["forward", "jump", "jump", "forward", "turnLeft", "jump", "jump", "turnLeft", "jump", "jump", "jump"],
      },
    ],
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = ROBO_STORIES;
}
